import streamlit as st
import pandas as pd
import plotly.graph_objects as go

from dashboard.ui.theme import render_page_title
from dashboard.data import get_price_history, get_products_list, get_saved_forecasts


@st.cache_data(ttl=900)
def _get_forecast_data(product_label):
    history_df = get_price_history(product_label)
    forecast_df = get_saved_forecasts(product_label)
    return history_df, forecast_df


def render_forecast_tab():
    render_page_title(
        "🔮 AI Price Forecast — Next 3 Weeks",
        "Random Forest forecast generated by scheduled pipeline.",
    )
    st.caption("Forecast values are precomputed and stored in the database by model job runs.")

    products_df = get_products_list()
    if products_df.empty:
        st.warning("No products available.")
        return

    product_label = st.selectbox("Product:", products_df["label"].tolist(), key="forecast_product")
    history_df, forecast_df = _get_forecast_data(product_label)

    if forecast_df.empty:
        st.warning("No saved price forecasts found. Run pipeline (python main.py) to generate fresh forecasts.")
        return

    store_options = ["Select Store"] + sorted(forecast_df["store"].dropna().unique().tolist())
    selected_store = st.selectbox("Store:", store_options, key="forecast_store")

    if selected_store == "Select Store":
        st.info("Select a store to view its forecast.")
        return

    data = forecast_df[forecast_df["store"] == selected_store].copy()
    hist_store = history_df[history_df["store"] == selected_store].copy() if not history_df.empty else pd.DataFrame()

    if data.empty:
        st.warning("No saved forecast rows for this store.")
        return

    data["date"] = pd.to_datetime(data["date"], errors="coerce")
    for col in ["price_pred", "price_low", "price_high"]:
        data[col] = pd.to_numeric(data[col], errors="coerce").fillna(0.0).clip(lower=0.0)
    data = data.sort_values("date")

    confidence = str(data["confidence_level"].dropna().iloc[-1]) if data["confidence_level"].notna().any() else "Unknown"
    training_points = int(pd.to_numeric(data["training_points"], errors="coerce").fillna(0).max())

    if not hist_store.empty:
        hist_store["scraped_at"] = pd.to_datetime(hist_store["scraped_at"], errors="coerce")
        hist_store["price"] = pd.to_numeric(hist_store["price"], errors="coerce")
        hist_store = hist_store.dropna(subset=["scraped_at", "price"])
        hist_store = hist_store.sort_values("scraped_at")

    st.subheader(f"📍 {selected_store}")
    st.caption(f"Model: Random Forest · Confidence: {confidence} — based on {training_points} historical weekly points")

    fig = go.Figure()
    if not hist_store.empty:
        fig.add_trace(
            go.Scatter(
                x=hist_store["scraped_at"],
                y=hist_store["price"],
                name="Historical",
                mode="lines+markers",
                line=dict(color="#4E79A7", width=2),
                marker=dict(size=6, color="#4E79A7"),
            )
        )

    fig.add_trace(
        go.Scatter(
            x=data["date"],
            y=data["price_pred"],
            name="Predicted",
            mode="lines+markers",
            line=dict(color="#C9A84C", width=2),
            marker=dict(size=7, color="#C9A84C"),
        )
    )
    fig.add_trace(
        go.Scatter(
            x=list(data["date"]) + list(data["date"])[::-1],
            y=list(data["price_high"]) + list(data["price_low"])[::-1],
            fill="toself",
            fillcolor="rgba(201,168,76,0.12)",
            line=dict(color="rgba(255,255,255,0)"),
            name="Confidence Range",
        )
    )
    fig.update_layout(
        height=380,
        template="plotly_white",
        hovermode="x unified",
        yaxis_tickprefix="€",
        yaxis_tickformat=".2f",
        yaxis_rangemode="tozero",
    )
    st.plotly_chart(fig, use_container_width=True)

    display = data[["date", "price_pred", "price_low", "price_high"]].copy()
    display["price_pred"] = display["price_pred"].apply(lambda x: f"€{x:.2f}")
    display["price_low"] = display["price_low"].apply(lambda x: f"€{x:.2f}")
    display["price_high"] = display["price_high"].apply(lambda x: f"€{x:.2f}")
    display["date"] = display["date"].dt.strftime("%Y-%m-%d")
    display.columns = ["Week", "Predicted", "Low", "High"]
    st.dataframe(display, use_container_width=True, hide_index=True)
